backend:
  image:
    repository: ghcr.io/kriipke/chartpress/api
    tag: main
  service:
    type: ClusterIP
    port: 8080

frontend:
  image:
    repository: ghcr.io/kriipke/chartpress/web
    tag: main
  service:
    type: ClusterIP
    port: 80
