backend:
  image:
    repository: ghcr.io/kriipke/chartpress/api
    tag: 0.1.11-rc3
  service:
    type: ClusterIP
    port: 8080

frontend:
  image:
    repository: ghcr.io/kriipke/chartpress/web
    tag: 0.1.11-rc3
  service:
    type: ClusterIP
    port: 80

ingress:
  class: nginx
  rewriteTarget: /
  host: ziinc.dev
  secretName: cert-wcard
  path: /chartpress/
  backend:
    service: chartpress-frontend
    port: 80

certificate:
  name: cert-wcard
  secretName: cert-wcard
  issuerName: letsencrypt-wcard
  commonName: ziinc.dev
  dnsNames:
    - "*.ziinc.dev"
    - "ziinc.dev"

issuer:
  name: letsencrypt-wcard
  acme:
    email: kriipke@protonmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef: letsencrypt-wcard
    dnsimple:
      groupName: acme.dnsimple.com
      solverName: dnsimple
      accountID: ""
      tokenSecretRef:
        name: dnsimple-dns
        key: token
