backend:
  image:
    repository: ghcr.io/kriipke/chartpress/api
    tag: latest
  service:
    type: ClusterIP
    port: 8080

frontend:
  image:
    repository: ghcr.io/kriipke/chartpress
    tag: latest
  service:
    type: ClusterIP
    port: 80
