apiVersion: v1
kind: Service
metadata:
  name: chartpress-backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
  selector:
    app: chartpress-backend
