apiVersion: v1
data:
  "default.conf": |+
    server {
        listen       80;
        listen  [::]:80;
        server_name  kubedash.io;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri /index.html;
        }

        location /generate {
            proxy_pass http://chartpress-frontend:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
