apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartpress-frontend
  labels:
    app: chartpress-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chartpress-frontend
  template:
    metadata:
      labels:
        app: chartpress-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
