apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chartpress.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.class }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.secretName | default .Values.certificate.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ trimSuffix "/" .Values.ingress.path }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.ingress.backend.service }}
                port:
                  number: {{ .Values.ingress.backend.port }}
