apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    email: {{ .Values.issuer.acme.email }}
    server: {{ .Values.issuer.acme.server }}
    privateKeySecretRef:
      name: {{ .Values.issuer.acme.privateKeySecretRef }}
    solvers:
      - dns01:
          webhook:
            groupName: {{ .Values.issuer.acme.dnsimple.groupName | quote }}
            solverName: {{ .Values.issuer.acme.dnsimple.solverName | quote }}
            config:
              tokenSecretRef:
                name: {{ .Values.issuer.acme.dnsimple.tokenSecretRef.name }}
                key: {{ .Values.issuer.acme.dnsimple.tokenSecretRef.key }}
              {{- with .Values.issuer.acme.dnsimple.accountID }}
              accountID: {{ . | quote }}
              {{- end }}
