// internal/engine/dependencies.go
//
// The infrastructure-dependency registry and its emission. Self-hosted
// infrastructure (databases, caches, brokers) is NOT generated as a subchart —
// generated templates are for the developer's own code. Instead chartpress
// emits an umbrella Chart.yaml `dependencies:` entry from the curated,
// version-pinned registry (dependencies.json), plus a values-block skeleton
// and a HANDOFF item. Keys the registry knows get a pinned upstream chart with
// a review-version TODO; anything else degrades to a stub entry whose
// repository/version are TODO markers. chartpress decides nothing about *where*
// an unknown dependency comes from — that stays a visible TODO.
package engine

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"helm.sh/helm/v3/pkg/chart"
)

//go:embed dependencies.json
var dependenciesJSON []byte

// DependencyEntry is one registry row: a pinned upstream chart.
type DependencyEntry struct {
	Label      string `json:"label"`
	Chart      string `json:"chart"`
	Repository string `json:"repository"`
	Version    string `json:"version"`
}

var dependencyRegistry map[string]DependencyEntry

func init() {
	var reg struct {
		Dependencies map[string]DependencyEntry `json:"dependencies"`
	}
	if err := json.Unmarshal(dependenciesJSON, &reg); err != nil {
		panic(fmt.Sprintf("engine: embedded dependencies.json is invalid: %v", err))
	}
	dependencyRegistry = reg.Dependencies
}

// DependencyByKey looks up a registry entry; ok is false for unknown keys
// (which the caller emits as a TODO stub).
func DependencyByKey(key string) (DependencyEntry, bool) {
	e, ok := dependencyRegistry[key]
	return e, ok
}

// DependencyKeys returns the registry keys in a stable (sorted) order — the
// closed set text-to-config may classify infrastructure into.
func DependencyKeys() []string {
	keys := make([]string, 0, len(dependencyRegistry))
	for k := range dependencyRegistry {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// applyDependencies emits the umbrella-level infrastructure dependencies: a
// Chart.yaml dependencies: entry per spec.Dependencies key, a values skeleton
// under each key, and (handled in handoff.go) a finishing checklist item.
// Must run after renameChart so the values text carries the real umbrella name.
func applyDependencies(ch *chart.Chart, spec Spec) error {
	if len(spec.Dependencies) == 0 {
		return nil
	}
	var valuesBlocks []string
	for _, key := range spec.Dependencies {
		entry, known := DependencyByKey(key)
		if known {
			ch.Metadata.Dependencies = append(ch.Metadata.Dependencies, &chart.Dependency{
				Name:       entry.Chart,
				Version:    entry.Version,
				Repository: entry.Repository,
				Alias:      key,
			})
			valuesBlocks = append(valuesBlocks, fmt.Sprintf(
				"# %s — upstream chart %s %s (%s).\n"+
					"# TODO(chartpress): review the pinned version, then set the values this\n"+
					"# dependency needs (auth, persistence, resources). See its chart docs.\n"+
					"%s: {}",
				entry.Label, entry.Chart, entry.Version, entry.Repository, key))
		} else {
			// Unknown infrastructure: emit the stanza shape with TODO markers.
			// chartpress does not guess a repository.
			ch.Metadata.Dependencies = append(ch.Metadata.Dependencies, &chart.Dependency{
				Name:       key,
				Version:    "TODO",                       // TODO(chartpress): pin a version
				Repository: "https://example.com/charts", // TODO(chartpress): set the repository
			})
			valuesBlocks = append(valuesBlocks, fmt.Sprintf(
				"# %s — TODO(chartpress): choose the upstream chart, pin its repository and\n"+
					"# version in Chart.yaml, then configure it here.\n"+
					"%s: {}",
				key, key))
		}
	}
	block := "# Generated by chartpress: values for umbrella infrastructure dependencies.\n" +
		"# These are self-hosted infrastructure run from mature upstream charts, not\n" +
		"# generated subcharts (see docs/best-practices.adoc).\n" +
		strings.Join(valuesBlocks, "\n")
	return appendValues(ch, block)
}

// dependencyHandoffItems returns the HANDOFF platform checklist lines for the
// spec's infrastructure dependencies.
func dependencyHandoffItems(spec Spec) []string {
	var items []string
	for _, key := range spec.Dependencies {
		if entry, known := DependencyByKey(key); known {
			items = append(items, fmt.Sprintf(
				"Dependency %q: review the pinned %s version (%s) and set its values (auth, persistence, resources).",
				key, entry.Label, entry.Version))
		} else {
			items = append(items, fmt.Sprintf(
				"Dependency %q: choose the upstream chart, pin its repository/version in Chart.yaml, and configure it.", key))
		}
	}
	return items
}
