// internal/engine/description_test.go
package engine

import "testing"

func TestDescriptionsLandInChartYaml(t *testing.T) {
	spec := Normalize(Spec{
		UmbrellaChartName: "demo",
		Description:       "the umbrella",
		Subcharts: []Subchart{
			{Name: "api", Workload: "deployment", Description: "the api"},
			{Name: "cache", Workload: "deployment"}, // empty -> fallback
		},
		Rules: DefaultRules(),
	})
	ch, err := BuildChart(spec, testdataTemplates)
	if err != nil {
		t.Fatalf("BuildChart: %v", err)
	}
	if ch.Metadata.Description != "the umbrella" {
		t.Fatalf("umbrella desc = %q", ch.Metadata.Description)
	}
	deps := map[string]string{}
	for _, d := range ch.Dependencies() {
		deps[d.Metadata.Name] = d.Metadata.Description
	}
	if deps["api"] != "the api" {
		t.Fatalf("api desc = %q", deps["api"])
	}
	if deps["cache"] != "cache chart generated by chartpress" {
		t.Fatalf("cache fallback desc = %q", deps["cache"])
	}
}
