// internal/engine/engine.go
package engine

import (
	"fmt"
	"path/filepath"
	"strings"

	"helm.sh/helm/v3/pkg/chart"
	"helm.sh/helm/v3/pkg/chart/loader"
	"helm.sh/helm/v3/pkg/chartutil"
)

const placeholderName = "umbrella-chart" // the literal name inside templates/umbrella

// BuildChart assembles the umbrella chart in memory from spec. spec must already
// be Normalized; BuildChart validates it and returns an error for any invalid
// input before touching the filesystem. templatesDir must contain "umbrella" and
// "subchart" subdirectories.
func BuildChart(spec Spec, templatesDir string) (*chart.Chart, error) {
	if err := Validate(spec); err != nil {
		return nil, fmt.Errorf("invalid spec: %w", err)
	}
	umbrellaPath := filepath.Join(templatesDir, "umbrella")
	subchartPath := filepath.Join(templatesDir, "subchart")

	umbrella, err := loader.Load(umbrellaPath)
	if err != nil {
		return nil, fmt.Errorf("load umbrella: %w", err)
	}
	renameChart(umbrella, spec.UmbrellaChartName)
	umbrella.Metadata.Description = chartDescription(spec.Description, spec.UmbrellaChartName)
	// Replace the template repo's placeholder values with a values.yaml derived
	// from the spec. setValues keeps Raw (what SaveDir writes) and Values (what
	// rendering uses) in sync — see values.go.
	if err := setValues(umbrella, umbrellaValuesText(spec)); err != nil {
		return nil, err
	}

	// For linked_templates: false, collect the umbrella's named-template bodies
	// AFTER rename so the inlined defines carry the umbrella-name prefix that the
	// subchart's (also-renamed) include stubs reference. This makes each subchart
	// self-contained and standalone-renderable (design §4.2); collecting a pristine,
	// un-renamed copy would leave dangling umbrella-chart.* defines that none of the
	// subchart's <umbrella>.* includes resolve.
	var inlineDefines string
	if !spec.Rules.LinkedTemplates {
		inlineDefines = collectUmbrellaDefines(umbrella)
	}

	for _, sc := range spec.Subcharts {
		sub, err := loader.Load(subchartPath)
		if err != nil {
			return nil, fmt.Errorf("load subchart template: %w", err)
		}
		if err := buildSubchart(sub, sc, spec, inlineDefines); err != nil {
			return nil, fmt.Errorf("subchart %q: %w", sc.Name, err)
		}
		umbrella.AddDependency(sub)
		umbrella.Metadata.Dependencies = append(umbrella.Metadata.Dependencies, &chart.Dependency{
			Name:       sc.Name,
			Version:    sub.Metadata.Version,
			Repository: fmt.Sprintf("file://charts/%s", sc.Name),
		})
	}

	if err := applyUmbrellaRules(umbrella, spec); err != nil {
		return nil, err
	}
	return umbrella, nil
}

// GenerateChart builds and writes the chart under outputRoot/<name>, returning the
// chart directory.
func GenerateChart(spec Spec, templatesDir, outputRoot string) (string, error) {
	ch, err := BuildChart(spec, templatesDir)
	if err != nil {
		return "", err
	}
	if err := chartutil.SaveDir(ch, outputRoot); err != nil {
		return "", fmt.Errorf("save chart: %w", err)
	}
	return filepath.Join(outputRoot, spec.UmbrellaChartName), nil
}

func chartDescription(desc, name string) string {
	if strings.TrimSpace(desc) != "" {
		return desc
	}
	return fmt.Sprintf("%s chart generated by chartpress", name)
}

// renameChart replaces the placeholder umbrella name across metadata, templates,
// and files.
func renameChart(ch *chart.Chart, newName string) {
	old := ch.Metadata.Name
	ch.Metadata.Name = newName
	for _, t := range ch.Templates {
		t.Data = []byte(strings.ReplaceAll(string(t.Data), old, newName))
	}
	for _, f := range ch.Files {
		f.Data = []byte(strings.ReplaceAll(string(f.Data), old, newName))
	}
}

// buildSubchart renames the subchart and applies per-subchart rules. The
// templates/tests/ guards ship with the chart: defaults render cleanly, and the
// guards fail fast on invalid user edits.
func buildSubchart(sub *chart.Chart, sc Subchart, spec Spec, inlineDefines string) error {
	sub.Metadata.Name = sc.Name
	sub.Metadata.Description = chartDescription(sc.Description, sc.Name)
	applyWorkload(sub, sc.Workload)
	replacePlaceholders(sub, placeholderName, spec.UmbrellaChartName, "component", sc.Name)
	applyCommonAnnotationsSubchart(sub, spec)
	applyResourceNaming(sub, spec.Rules.ResourceNamesMatchChartName)
	applySubchartFileToggles(sub, spec.Rules)
	if block := generatedSubchartValues(sc, spec); block != "" {
		if err := appendValues(sub, block); err != nil {
			return err
		}
	}
	applyIngress(sub, spec.Rules.Ingress)
	if !spec.Rules.LinkedTemplates {
		applyInlining(sub, inlineDefines)
	}
	return nil
}

// replacePlaceholders substitutes placeholder tokens across the chart's templates
// and files. oldnew is a flat (old, new, old, new, ...) sequence, applied in a
// single left-to-right pass via strings.Replacer: matches do not overlap and
// already-substituted text is never re-scanned. This keeps replacement
// deterministic and correct even when a substitution value contains another
// placeholder token (e.g. an umbrella name like "my-component" that embeds the
// "component" placeholder) — a map-based, unordered, repeated-ReplaceAll loop
// could otherwise corrupt it depending on iteration order.
func replacePlaceholders(ch *chart.Chart, oldnew ...string) {
	r := strings.NewReplacer(oldnew...)
	for _, t := range ch.Templates {
		t.Data = []byte(r.Replace(string(t.Data)))
	}
	for _, f := range ch.Files {
		f.Data = []byte(r.Replace(string(f.Data)))
	}
	// values.yaml lives in ch.Raw (not Templates/Files); replace there too so
	// comments mentioning the placeholders stay coherent, and re-sync ch.Values.
	if txt := rawValues(ch); txt != "" {
		if replaced := r.Replace(txt); replaced != txt {
			// The placeholders only ever appear in comments/strings, so the
			// replaced text stays valid YAML; setValues re-parses defensively.
			_ = setValues(ch, replaced)
		}
	}
}

// applyUmbrellaRules applies the umbrella-level rules. Rule-driven values keys
// (global.commonAnnotations, global.sharedSecrets, global.newrelic) are seeded
// by umbrellaValuesText in BuildChart.
func applyUmbrellaRules(ch *chart.Chart, spec Spec) error {
	applyUmbrellaFileToggles(ch, spec.Rules)
	applySharedSecretsUmbrella(ch, spec)
	applySharedNewrelicUmbrella(ch, spec)
	return nil
}
