// internal/engine/engine.go
package engine

import (
	"fmt"
	"path/filepath"
	"strings"

	"helm.sh/helm/v3/pkg/chart"
	"helm.sh/helm/v3/pkg/chart/loader"
	"helm.sh/helm/v3/pkg/chartutil"
)

const placeholderName = "umbrella-chart" // the literal name inside templates/umbrella

// BuildChart assembles the umbrella chart in memory from spec. templatesDir must
// contain "umbrella" and "subchart" subdirectories.
func BuildChart(spec Spec, templatesDir string) (*chart.Chart, error) {
	umbrellaPath := filepath.Join(templatesDir, "umbrella")
	subchartPath := filepath.Join(templatesDir, "subchart")

	umbrella, err := loader.Load(umbrellaPath)
	if err != nil {
		return nil, fmt.Errorf("load umbrella: %w", err)
	}
	renameChart(umbrella, spec.UmbrellaChartName)
	umbrella.Metadata.Description = chartDescription(spec.Description, spec.UmbrellaChartName)
	// Clear the umbrella's example values — the generated chart starts with
	// clean values; subchart defaults come from each subchart's own values.yaml.
	umbrella.Values = map[string]interface{}{}

	for _, sc := range spec.Subcharts {
		sub, err := loader.Load(subchartPath)
		if err != nil {
			return nil, fmt.Errorf("load subchart template: %w", err)
		}
		if err := buildSubchart(sub, sc, spec); err != nil {
			return nil, fmt.Errorf("subchart %q: %w", sc.Name, err)
		}
		umbrella.AddDependency(sub)
		umbrella.Metadata.Dependencies = append(umbrella.Metadata.Dependencies, &chart.Dependency{
			Name:       sc.Name,
			Version:    sub.Metadata.Version,
			Repository: fmt.Sprintf("file://charts/%s", sc.Name),
		})
	}

	if err := applyUmbrellaRules(umbrella, spec); err != nil {
		return nil, err
	}
	return umbrella, nil
}

// GenerateChart builds and writes the chart under outputRoot/<name>, returning the
// chart directory.
func GenerateChart(spec Spec, templatesDir, outputRoot string) (string, error) {
	ch, err := BuildChart(spec, templatesDir)
	if err != nil {
		return "", err
	}
	if err := chartutil.SaveDir(ch, outputRoot); err != nil {
		return "", fmt.Errorf("save chart: %w", err)
	}
	return filepath.Join(outputRoot, spec.UmbrellaChartName), nil
}

func chartDescription(desc, name string) string {
	if strings.TrimSpace(desc) != "" {
		return desc
	}
	return fmt.Sprintf("%s chart generated by chartpress", name)
}

// renameChart replaces the placeholder umbrella name across metadata, templates,
// values, and files.
func renameChart(ch *chart.Chart, newName string) {
	old := ch.Metadata.Name
	ch.Metadata.Name = newName
	for _, t := range ch.Templates {
		t.Data = []byte(strings.ReplaceAll(string(t.Data), old, newName))
	}
	for _, f := range ch.Files {
		f.Data = []byte(strings.ReplaceAll(string(f.Data), old, newName))
	}
}

// buildSubchart renames the subchart and applies per-subchart rules. Rule-specific
// behavior is filled in by later tasks; for now it only renames.
func buildSubchart(sub *chart.Chart, sc Subchart, spec Spec) error {
	sub.Metadata.Name = sc.Name
	sub.Metadata.Description = chartDescription(sc.Description, sc.Name)
	// Strip test-only templates (templates/tests/) that require user-supplied
	// values and would cause render failures during in-process chart assembly.
	filtered := sub.Templates[:0]
	for _, t := range sub.Templates {
		if !strings.HasPrefix(t.Name, "templates/tests/") {
			filtered = append(filtered, t)
		}
	}
	sub.Templates = filtered
	applyWorkload(sub, sc.Workload)
	replacePlaceholders(sub, map[string]string{
		placeholderName: spec.UmbrellaChartName,
		"component":     sc.Name,
	})
	applyResourceNaming(sub, spec.Rules.ResourceNamesMatchChartName)
	applySubchartFileToggles(sub, spec.Rules)
	return nil
}

func replacePlaceholders(ch *chart.Chart, repl map[string]string) {
	apply := func(b []byte) []byte {
		s := string(b)
		for old, nw := range repl {
			s = strings.ReplaceAll(s, old, nw)
		}
		return []byte(s)
	}
	for _, t := range ch.Templates {
		t.Data = apply(t.Data)
	}
	for _, f := range ch.Files {
		f.Data = apply(f.Data)
	}
}

// applyUmbrellaRules is the umbrella-level rule hook; later tasks add behavior.
func applyUmbrellaRules(ch *chart.Chart, spec Spec) error {
	applyUmbrellaFileToggles(ch, spec.Rules)
	return nil
}
