// internal/engine/handoff_test.go
package engine

import (
	"strings"
	"testing"

	"helm.sh/helm/v3/pkg/chart"
)

func umbrellaFile(ch *chart.Chart, name string) string {
	for _, f := range ch.Files {
		if f.Name == name {
			return string(f.Data)
		}
	}
	return ""
}

func TestHandoffGeneratedByDefault(t *testing.T) {
	spec := patternSpec(
		Subchart{Name: "orders", Pattern: "api-microservice"},
		Subchart{Name: "emailer", Pattern: "worker"},
		Subchart{Name: "dispatcher", Pattern: "scheduler"},
	)
	ch, err := BuildChart(spec, testdataTemplates)
	if err != nil {
		t.Fatalf("BuildChart: %v", err)
	}
	h := umbrellaFile(ch, "HANDOFF.md")
	if h == "" {
		t.Fatalf("HANDOFF.md must be generated by default")
	}
	for _, want := range []string{
		"## Ground rules",
		"## Platform",
		"## charts/orders — API microservice",
		"## charts/emailer — Job executor / queue worker",
		"## charts/dispatcher — Scheduler / singleton controller",
		"liveness signal",                // worker checklist content
		"Do NOT raise the replica count", // scheduler checklist content
		"## Done means",
	} {
		if !strings.Contains(h, want) {
			t.Fatalf("HANDOFF.md missing %q:\n%s", want, h)
		}
	}
}

func TestHandoffGateAndToggleIndependence(t *testing.T) {
	spec := patternSpec(Subchart{Name: "api"})
	off := false
	spec.Rules.GenerateHandoff = &off
	ch, err := BuildChart(spec, testdataTemplates)
	if err != nil {
		t.Fatalf("BuildChart: %v", err)
	}
	if umbrellaFile(ch, "HANDOFF.md") != "" {
		t.Fatalf("generate_handoff: false must suppress HANDOFF.md")
	}
	// The unconditional contract files are not affected by the handoff gate.
	for _, keep := range []string{"AGENTS.md", "CLAUDE.md", "docs/best-practices.adoc"} {
		if umbrellaFile(ch, keep) == "" {
			t.Fatalf("%s must survive generate_handoff: false", keep)
		}
	}
}

func TestHandoffCarriesWarningsAndOverrides(t *testing.T) {
	spec := patternSpec(
		Subchart{Name: "bff", Pattern: "edge-gateway"},
		Subchart{Name: "orders", Pattern: "api-microservice"},
		Subchart{Name: "pricing", Pattern: "grpc-service", Ingress: boolPtr(true)},
	)
	ch, err := BuildChart(spec, testdataTemplates)
	if err != nil {
		t.Fatalf("BuildChart: %v", err)
	}
	h := umbrellaFile(ch, "HANDOFF.md")
	if !strings.Contains(h, "edge gateway") {
		t.Fatalf("handoff platform section must carry the validation warnings:\n%s", h)
	}
	if !strings.Contains(h, "Explicit overrides: ingress") {
		t.Fatalf("handoff must flag trait overrides:\n%s", h)
	}
	if !strings.Contains(h, "External gRPC") {
		t.Fatalf("ingress override on grpc-service must add the external-gRPC item:\n%s", h)
	}
}
