// internal/engine/values.go
//
// Values handling: helm's chartutil.Save/SaveDir write values.yaml from
// chart.Raw (the original file bytes), NOT from the parsed chart.Values map.
// Mutating only chart.Values therefore produces charts whose saved values.yaml
// silently lacks the mutation while in-memory rendering sees it. Every values
// edit in the engine goes through setValues, which updates BOTH.
//
// Values files are authored as text (not marshaled from maps) so the generated
// chart keeps its comments — for a starter chart the comments are half the
// deliverable.
package engine

import (
	"fmt"
	"strings"

	"helm.sh/helm/v3/pkg/chart"
	"sigs.k8s.io/yaml"
)

const valuesFileName = "values.yaml"

// rawValues returns the chart's values.yaml source text ("" if absent).
func rawValues(ch *chart.Chart) string {
	for _, f := range ch.Raw {
		if f.Name == valuesFileName {
			return string(f.Data)
		}
	}
	return ""
}

// setValues replaces the chart's values.yaml source text and reparses it into
// ch.Values, keeping the saved artifact and in-memory rendering in sync.
func setValues(ch *chart.Chart, text string) error {
	vals := map[string]interface{}{}
	if err := yaml.Unmarshal([]byte(text), &vals); err != nil {
		return fmt.Errorf("values for chart %q: %w", ch.Name(), err)
	}
	data := []byte(text)
	found := false
	for _, f := range ch.Raw {
		if f.Name == valuesFileName {
			f.Data = data
			found = true
		}
	}
	if !found {
		ch.Raw = append(ch.Raw, &chart.File{Name: valuesFileName, Data: data})
	}
	ch.Values = vals
	return nil
}

// appendValues appends a YAML block (top-level keys) to the chart's values.yaml.
// The block must not repeat keys that already exist in the file.
func appendValues(ch *chart.Chart, block string) error {
	cur := strings.TrimRight(rawValues(ch), "\n")
	return setValues(ch, cur+"\n\n"+strings.TrimRight(block, "\n")+"\n")
}

// umbrellaValuesText renders the umbrella chart's values.yaml from the spec: a
// global block (plus rule-driven keys) and one stanza per subchart with the
// values a developer edits first.
func umbrellaValuesText(spec Spec) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Values for the %s umbrella chart, generated by chartpress.\n", spec.UmbrellaChartName)
	b.WriteString("# Keys under each subchart's name override that subchart's own values.yaml.\n")
	b.WriteString("#\n")
	b.WriteString("# Finish-the-chart checklist: search for TODO(chartpress) here and in each\n")
	b.WriteString("# subchart's values.yaml.\n\n")
	b.WriteString("global:\n")
	b.WriteString("  # Registry/organization prefix applied to every subchart image\n")
	b.WriteString("  # (override per subchart with <name>.image.registry).\n")
	b.WriteString("  repository: registry.example.com/CHANGEME # TODO(chartpress): set your registry\n")
	if spec.Rules.CommonAnnotations {
		b.WriteString("  # Annotations merged onto every resource of every subchart.\n")
		b.WriteString("  commonAnnotations:\n")
		fmt.Fprintf(&b, "    app.kubernetes.io/part-of: %s\n", spec.UmbrellaChartName)
		b.WriteString("    chartpress.dev/managed: \"true\"\n")
	}
	if spec.Rules.SharedSecretsConfig {
		fmt.Fprintf(&b, "  # Key/value pairs rendered into the %s-shared-secrets Secret\n", spec.UmbrellaChartName)
		b.WriteString("  # and injected into every subchart via envFrom.\n")
		b.WriteString("  sharedSecrets:\n")
		b.WriteString("    data: {}\n")
	}
	if spec.Rules.SharedNewrelicConfig {
		b.WriteString("  newrelic:\n")
		b.WriteString("    licenseKey: \"\" # TODO(chartpress): set your New Relic license key\n")
	}
	for _, sc := range spec.Subcharts {
		fmt.Fprintf(&b, "\n%s:\n", sc.Name)
		b.WriteString("  image:\n")
		fmt.Fprintf(&b, "    name: %s\n", sc.Name)
		b.WriteString("    tag: \"latest\" # TODO(chartpress): pin your image tag\n")
	}
	return b.String()
}

// generatedSubchartValues returns the values block chartpress appends to a
// subchart's values.yaml: env/envFrom wiring for the shared-config rules
// (skipped when the subchart's shared_env trait is off — the umbrella-level
// Secret/ConfigMap still render for the subcharts that do consume them) and
// the HPA target kind for non-deployment workloads. Empty when nothing
// applies.
func generatedSubchartValues(sc Subchart, rt ResolvedTraits, spec Spec) string {
	var envFrom, env []string
	if rt.SharedEnv {
		if spec.Rules.SharedSecretsConfig {
			envFrom = append(envFrom,
				"  - secretRef:\n      name: "+spec.UmbrellaChartName+"-shared-secrets")
		}
		if spec.Rules.SharedNewrelicConfig {
			envFrom = append(envFrom,
				"  - configMapRef:\n      name: "+spec.UmbrellaChartName+"-newrelic-config")
			env = append(env,
				"  - name: NEW_RELIC_LICENSE_KEY\n    valueFrom:\n      secretKeyRef:\n        name: "+
					spec.UmbrellaChartName+"-newrelic-license\n        key: NEW_RELIC_LICENSE_KEY",
				"  - name: NEW_RELIC_APP_NAME\n    value: "+sc.Name)
		}
	}

	var b strings.Builder
	if len(envFrom) > 0 || len(env) > 0 {
		b.WriteString("# Generated by chartpress: wiring for umbrella-level shared config.\n")
	}
	if len(envFrom) > 0 {
		b.WriteString("envFrom:\n" + strings.Join(envFrom, "\n") + "\n")
	}
	if len(env) > 0 {
		b.WriteString("env:\n" + strings.Join(env, "\n") + "\n")
	}
	if rt.Workload == "statefulset" {
		b.WriteString("# Generated by chartpress: HPA scale target kind for this workload.\n")
		b.WriteString("workloadKind: StatefulSet\n")
	}
	return b.String()
}
