apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    email: {{ .Values.issuer.acme.email }}
    server: {{ .Values.issuer.acme.server }}
    privateKeySecretRef:
      name: {{ .Values.issuer.acme.privateKeySecretRef }}
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: {{ .Values.issuer.acme.solverSecret.name }}
              key: {{ .Values.issuer.acme.solverSecret.key }}
