name: Container Build - API

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'api.go'
      - '.github/workflows/build-api.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-api:
    uses: ./.github/workflows/docker-build-publish.yaml
    with:
      context: .
      dockerfile: ./Dockerfile
      image-name: api
