name: Build and Publish API Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'api.go'
      - '.github/workflows/build-api.yaml'
  workflow_dispatch:

jobs:
  build-api:
    uses: ./.github/workflows/docker-build-publish.yaml
    with:
      context: .
      dockerfile: ./Dockerfile
      image-name: api
