# SPDX-License-Identifier: Apache-2.0
name: Container Build - WEB

on:
  push:
    branches:
      - main
    paths:
      - 'web/Dockerfile'
      - 'web/**'
      - '.github/workflows/build-web.yaml'
      - '.github/workflows/docker-build-publish.yaml'
      - '.github/workflows/verify.yaml'
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml

  build-web:
    needs: verify
    uses: ./.github/workflows/docker-build-publish.yaml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      context: ./web
      dockerfile: ./web/Dockerfile
      image-name: web
