name: Build and Publish Web Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'web/Dockerfile'
      - 'web/**'
      - '.github/workflows/build-web.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-web:
    uses: ./.github/workflows/docker-build-publish.yaml
    with:
      context: ./web
      dockerfile: ./web/Dockerfile
      image-name: web
